import imgUrl from '../../img/filhotes1.jpeg'
export const incidents = [
  {
    id: 1,
    title: 'Filhotinhos abandonados pelo dono',
    description: 'Alguns filhotinhos foram encontrados na rua, dentro de uma caixa de papelão. 4 filhotes.',
    image: '../../img/filhotes1.jpeg',
    location: 'Rua das Araras - Imbuí',
    status: 'Disponível',
  },
  {
    id: 2,
    title: 'Irmãos preparados para adoção',
    description: 'Duplinha de 9 meses procurando uma família para adota-los.',
    image: '../../img/filhotes2.jpg',
    location: 'Rua José Feitosa - Caminho das Arvores',
    status: 'Em entrevistas',
  },
  {
    id: 3,
    title: 'Gatinho encontrado em canteiro de obras',
    description: 'Encontrado sozinho em um canteiro de obras. JÁ VACINADO.',
    image: '../../img/filhotes3.jpg',
    location: 'Rua Eduardo Campos - Boca do Rio',
    status: 'Disponível',
  },
  {
    id: 4,
    title: '4 filhotes para adoção',
    description: 'Filhotinhos de 3 semanas para adoção.',
    image: '../../img/filhotes4.jpg',
    location: 'Rua da Felicidade - Bairro da Paz',
    status: 'Disponível',
  },
  {
    id: 5,
    title: 'Duplinha para adoção',
    description: 'Ambos foram encontrados juntos em avenida de Salvador.',
    image: '../../img/filhotes5.jpg',
    location: 'Rua Macapá - Ondina',
    status: 'Em entrevistas',
  },
  {
    id: 6,
    title: 'Thomas está para adoção',
    description: 'Filhotinho foi encontrado debaixo de telhas em uma casa abandonada na Federação.',
    image: '../../img/filhotes6.jpg',
    location: 'Rua Jardim Federação - Federação',
    status: 'Em entrevistas',
  },
  {
    id: 7,
    title: 'Gatinho para adoção',
    description: 'Joaquim foi abandonado perto da praia da barra por seu dono. JÁ VACINADO .',
    image: '../../img/filhotes7.jpg',
    location: 'Rua César Zama - Barra',
    status: 'Disponível',
  },
  {
    id: 8,
    title: '4 irmão para adoção',
    description: 'Esses 4 estão no aguardo de uma familia para chamar de sua!.',
    image: '../../img/filhotes8.jpg',
    location: 'Rua Parari - Brotas',
    status: 'Disponível',
  },
]
