import imgUrl from '../../img/filhotes1.jpeg'
export const incidents = [
  {
    id: 1,
    title: 'Filhotinhos encontrados',
    description: 'Alguns filhotinhos foram encontrados na estrada.',
    image: imgUrl,
    location: 'Rua das Araras - Imbuí',
    status: 'Disponível',
  },
  {
    id: 1,
    title: 'Filhotinhos encontrados',
    description: 'Alguns filhotinhos foram encontrados na estrada.',
    image: imgUrl,
    location: 'Rua das Araras - Imbuí',
    status: 'Em entrevistas',
  },
  {
    id: 1,
    title: 'Filhotinhos encontrados',
    description: 'Alguns filhotinhos foram encontrados na estrada.',
    image: imgUrl,
    location: 'Rua das Araras - Imbuí',
    status: 'Processando saída',
  },
  {
    id: 1,
    title: 'Filhotinhos encontrados',
    description: 'Alguns filhotinhos foram encontrados na estrada.',
    image: imgUrl,
    location: 'Rua das Araras - Imbuí',
    status: 'Disponível',
  },
  {
    id: 1,
    title: 'Filhotinhos encontrados',
    description: 'Alguns filhotinhos foram encontrados na estrada.',
    image: imgUrl,
    location: 'Rua das Araras - Imbuí',
    status: 'Disponível',
  },
  {
    id: 1,
    title: 'Filhotinhos encontrados',
    description: 'Alguns filhotinhos foram encontrados na estrada.',
    image: imgUrl,
    location: 'Rua das Araras - Imbuí',
    status: 'Disponível',
  },
  {
    id: 1,
    title: 'Filhotinhos encontrados',
    description: 'Alguns filhotinhos foram encontrados na estrada.',
    image: imgUrl,
    location: 'Rua das Araras - Imbuí',
    status: 'Disponível',
  },
  {
    id: 1,
    title: 'Filhotinhos encontrados',
    description: 'Alguns filhotinhos foram encontrados na estrada.',
    image: imgUrl,
    location: 'Rua das Araras - Imbuí',
    status: 'Disponível',
  },
]
