import imgUrl from '../../img/filhotes1.jpeg'
export const incidents = [
  {
    id: 1,
    title: 'Filhotinhos encontrados',
    description: 'Alguns filhotinhos foram encontrados na estrada.',
    image: imgUrl,
    location: 'Rua das Araras - Imbuí',
    contato: '(71) 99999-9999',
  },
  {
    id: 1,
    title: 'Filhotinhos encontrados',
    description: 'Alguns filhotinhos foram encontrados na estrada.',
    image: imgUrl,
    location: 'Rua das Araras - Imbuí',
    contato: '(71) 99999-9999',
  },
  {
    id: 1,
    title: 'Filhotinhos encontrados',
    description: 'Alguns filhotinhos foram encontrados na estrada.',
    image: imgUrl,
    location: 'Rua das Araras - Imbuí',
    contato: '(71) 99999-9999',
  },
  {
    id: 1,
    title: 'Filhotinhos encontrados',
    description: 'Alguns filhotinhos foram encontrados na estrada.',
    image: imgUrl,
    location: 'Rua das Araras - Imbuí',
    contato: '(71) 99999-9999',
  },
  {
    id: 1,
    title: 'Filhotinhos encontrados',
    description: 'Alguns filhotinhos foram encontrados na estrada.',
    image: imgUrl,
    location: 'Rua das Araras - Imbuí',
    contato: '(71) 99999-9999',
  },
  {
    id: 1,
    title: 'Filhotinhos encontrados',
    description: 'Alguns filhotinhos foram encontrados na estrada.',
    image: imgUrl,
    location: 'Rua das Araras - Imbuí',
    contato: '(71) 99999-9999',
  },
  {
    id: 1,
    title: 'Filhotinhos encontrados',
    description: 'Alguns filhotinhos foram encontrados na estrada.',
    image: imgUrl,
    location: 'Rua das Araras - Imbuí',
    contato: '(71) 99999-9999',
  },
  {
    id: 1,
    title: 'Filhotinhos encontrados',
    description: 'Alguns filhotinhos foram encontrados na estrada.',
    image: imgUrl,
    location: 'Rua das Araras - Imbuí',
    contato: '(71) 99999-9999',
  },
]
